const testID = {
  SCREEN: 'INSTRUMENT',
  button:{
    SELECT_ORDER_TYPE:'SELECT_ORDER_TYPE',
    REVIEW_ORDER:'REVIEW_ORDER',
    CANCEL:'CANCEL',
    CONTINUE:'CONTINUE',
    CREATE_SELL_LIMIT: 'CREATE_SELL_LIMIT',
    CREATE_BUY_LIMIT: 'CREATE_BUY_LIMIT',
    ORDER_DONE: 'ORDER_DONE'
  },
  label:{
    STOCK_NAME:'STOCK_NAME',
    CURRENT_BALANCE:'CURRENT_BALANCE',
    NUMBER_OF_SHARES:'NUMBER_OF_SHARES'
  },
  input:{
    BUY_PRICE:'BUY_PRICE',
    TOTAL_INVESTMENT:'TOTAL_INVESTMENT'
  }
};

export default testID;
